[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "nspr", "atk", "at-spi2-atk", "xorg.libX11", "xorg.libxcb", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "libgbm", "libxkbcommon", "alsa-lib"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node server.js"
